### ISSUE TITLE
Adicionar código base do projeto anterior

### ISSUE THREAD

**Issue by Ridersk** [deeplearningunb/deep-coin#11]
Como este projeto será a evolução de um projeto já existente <https://github.com/WelisonR/contador_moedas>, nesta issue precisamos importar o código base do projeto anterior e fazermos pequenas modificações para começarmos a aprimorarmos o tratamento do dataset a partir de testes e validações

## Tarefas

- [x] Importar função de criação do dataset (corte da moeda e redução do tamanho da imagem)
- [x] Importar função de frequência dos tipos de moedas
- [x] Importar função de extração das imagens para a memória
- [x] Importar função de mostrar a imagem da moeda e sua label correspondente
- [x] Rodar o projeto para verificar possíveis problemas de dependências
- [x] Alterar alguns nomes de variáveis que possam remeter ao projeto antigo (O projeto mudou de nome)

**Comment by WelisonR** [comment]
Issue reaberta para pequenos incrementos do PR #19.
