### ISSUE TITLE
Melhorar método de predição

### ISSUE THREAD

**Issue by lucianosz7** [deeplearningunb/deep-coin#15]
## Descrição

Atualmente, um dos empecilhos em relação a finalidade do projeto é a precisão dos resultados fornecidos pela rede neural convolucional (CNN). Nesse sentido, essa issue destina-se a testar diferentes modelagens para a CNN de forma a melhorar os resultados obtidos pela rede.

## Tarefas

- [x] Realizar mudanças para melhorar os resultados das predições;
- [x] Fazer testes para validar a acurácia da predição da rede neural convolucional.

**Comment by WelisonR** [comment]
Atualizei alguns critérios dessa atividade. Vamos conjuntamente tentar novas modelagens de rede para atingirmos resultados melhores, @lucianosz7 e @Ridersk.
